# myapp-kubernetes-manifests/k8s/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp-container
          image: your-docker-username/myapp:latest # This image name should match 'name' in kustomization.yaml
          ports:
            - containerPort: 80
