plugin: gcp_compute
projects:
  - mystical-vial-403905
auth_kind: serviceaccount
keyed_groups:
  - key: labels['ansible-group']
    prefix: ''
hostnames:
  - key: networkInterfaces[0].accessConfigs[0].natIP
compose:
  ansible_host: networkInterfaces[0].accessConfigs[0].natIP
