# ansible/inventory.gcp_compute.yml

plugin: gcp_compute
projects:
  # This correctly pulls the project ID from the CI environment.
  - "{{ lookup('env', 'CLOUDSDK_CORE_PROJECT') }}"

# [FIX] Removed the 'service_account_file' line.
# The plugin will now automatically use the GOOGLE_APPLICATION_CREDENTIALS
# environment variable set by the google-github-actions/auth step.
auth_kind: serviceaccount

filters:
  - "status = RUNNING"

hostnames:
  - key: networkInterfaces[0].accessConfigs[0].natIP

compose:
  ansible_host: networkInterfaces[0].accessConfigs[0].natIP

keyed_groups:
  - key: labels['ansible-group']
    prefix: ''

