

# ansible/inventory.gcp_compute.yml

plugin: gcp_compute
projects:
  # This correctly pulls the project ID from the CI environment.
  - "{{ lookup('env', 'CLOUDSDK_CORE_PROJECT') }}"

auth_kind: serviceaccount

# [FIX] Explicitly provide the service account credentials.
# Instead of a file path, this reads the JSON key directly from the
# GCP_SA_KEY secret, which is available as an environment variable.
service_account_contents: "{{ lookup('env', 'GCP_SA_KEY') }}"

filters:
  - "status = RUNNING"

hostnames:
  - key: networkInterfaces[0].accessConfigs[0].natIP

compose:
  ansible_host: networkInterfaces[0].accessConfigs[0].natIP

keyed_groups:
  - key: labels['ansible-group']
    prefix: ''
