
# ansible/playbook.yml

- name: Configure server and deploy application
  # [CHANGE] Target the specific 'web-server' group defined by the inventory file.
  hosts: web-server
  become: true
  gather_facts: false

  pre_tasks:
    - name: Wait for SSH to become available on the new instance
      wait_for_connection:
        timeout: 180 # Wait for up to 3 minutes
        delay: 10    # Check every 10 seconds

    - name: Gather facts after connection is established
      setup:

    - name: Ensure base packages for Docker are present
      apt:
        name:
          - python3
          - python3-pip
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: present
        update_cache: yes

  tasks:
    - name: Add Docker's official GPG key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Set up the Docker repository for Debian 11 (bullseye)
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/debian bullseye stable
        state: present

    - name: Install Docker Engine
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        update_cache: yes

    - name: Ensure Docker service is started and enabled on boot
      service:
        name: docker
        state: started
        enabled: yes

    # The community.docker.docker_container module requires the Docker SDK for Python on the TARGET host.
    - name: Install Docker SDK for Python
      pip:
        name: docker

    - name: Pull the latest application image and run the container
      community.docker.docker_container:
        name: calculator
        # This variable is passed from the GitHub Actions workflow
        image: "{{ docker_image }}"
        state: started
        restart_policy: always
        published_ports:
          # Map port 80 on the host to port 80 in the container
          - "80:80"
