---
- name: Configure server and deploy application
  hosts: all
  become: true
  gather_facts: false

  pre_tasks:
    - name: Wait for SSH to become available
      wait_for_connection:
        timeout: 180
        delay: 10

    - name: Gather facts
      setup:

    - name: Ensure base packages for Docker/Ansible are present
      apt:
        name:
          - python3
          - python3-pip
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: present
        update_cache: yes

  tasks:
    - name: Add Docker's official GPG key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Set up the Docker repository for Debian 11 (bullseye)
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/debian bullseye stable
        state: present

    - name: Install Docker Engine
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        update_cache: yes

    - name: Ensure Docker service is started and enabled
      service:
        name: docker
        state: started
        enabled: yes

    # docker_container module needs the Docker SDK for Python on the TARGET host
    - name: Install Python Docker SDK on the host
      pip:
        name: docker

    - name: Pull and run the application container
      community.docker.docker_container:
        name: calculator
        image: xaqani90/calc
        state: started
        restart_policy: always
        published_ports:
          - "80:80"
