---
- name: Configure server and deploy application
  hosts: all # This will target the VM we create
  become: yes # Use 'sudo' for tasks

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes
        cache_valid_time: 3600 # One hour

    - name: Install prerequisite packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: present

    - name: Add Docker's official GPG key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Set up the Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/debian buster stable
        state: present

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        update_cache: yes

    - name: Pull and run the application container
      docker_container:
        name: calculator
        image: xaqani90/calc # <-- IMPORTANT: Change this to your Docker image!
        state: started
        restart_policy: always
        published_ports:
          - "80:80" # Map container port 80 to host port 80