name: Deploy to GCP

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Auth action writes a temporary JSON file and sets GOOGLE_APPLICATION_CREDENTIALS for us
      - name: Authenticate to GCP
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Apply
        working-directory: ./terraform
        run: |
          terraform init
          terraform apply -auto-approve \
            -var="gcp_project_id=${{ secrets.GCP_PROJECT_ID }}" \
            -var="ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Ansible + collections
        run: |
          python -m pip install --upgrade pip
          pip install "ansible>=9.0.0" google-auth-httplib2 requests
          ansible-galaxy collection install google.cloud community.docker

      - name: Write Ansible config (enable gcp plugin)
        working-directory: ./ansible
        run: |
          cat > ansible.cfg <<'CFG'
          [defaults]
          host_key_checking = False
          inventory = ./inventory.gcp.yml
          callback_whitelist = profile_tasks

          [inventory]
          enable_plugins = gcp_compute, yaml, ini
          CFG

      - name: Check inventory (debug)
        working-directory: ./ansible
        env:
          # Auth action already exports GOOGLE_APPLICATION_CREDENTIALS
          CLOUDSDK_CORE_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
        run: ansible-inventory -i inventory.gcp.yml --list

      - name: Run Ansible Playbook
        working-directory: ./ansible
        env:
          CLOUDSDK_CORE_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

          ansible-playbook playbook.yml \
           -i inventory.gcp_compute.yml \
           --user ansible \
           --private-key private_key.pem
