name: CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        run: |
          # Use the GITHUB_SHA environment variable to create a unique tag.
          # We use 'cut' to get the first 7 characters for a shorter tag.
          IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-7)

          # Build the image with both the 'latest' and the unique commit tag.
          docker build -t ${{ secrets.DOCKER_USERNAME }}/myapp:${IMAGE_TAG} .
          # Push both tags to Docker Hub.
          docker push ${{ secrets.DOCKER_USERNAME }}/myapp:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/myapp:${IMAGE_TAG}
