name: CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        run: |
         IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-7)

         # Build image with both tags
         docker build -t ${{ secrets.DOCKER_USERNAME }}/myapp:${IMAGE_TAG} \
                 -t ${{ secrets.DOCKER_USERNAME }}/myapp:latest .

         # Push both tags to Docker Hub
         docker push ${{ secrets.DOCKER_USERNAME }}/myapp:${IMAGE_TAG}
         docker push ${{ secrets.DOCKER_USERNAME }}/myapp:latest

