# .github/workflows/ci.yml
name: Deploy to GCP

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Apply
        id: terraform
        working-directory: ./terraform
        run: |
          terraform init
          terraform apply -auto-approve \
            -var="gcp_project_id=${{ secrets.GCP_PROJECT_ID }}" \
            -var="ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # --- MODIFICATION START ---
      - name: Install Ansible and Google Cloud Collection
        run: |
          python -m pip install --upgrade pip
          pip install ansible "google-auth-httplib2>=0.1.0" "requests>=2.20.0"
          # This is the crucial missing step to install the GCP plugins
          ansible-galaxy collection install google.cloud
      # --- MODIFICATION END ---

      - name: Run Ansible Playbook
        working-directory: ./ansible
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

          ansible-playbook playbook.yml \
            -i inventory.gcp_compute.yml \
            --user ansible \
            --private-key private_key.pem
